"""Lightweight shared infrastructure for all RocqiPath feature packages.

Imaging backends used by :class:`SlideReader` are loaded lazily.
"""

from .console import (
    ask,
    print_banner,
    print_code,
    print_counts,
    print_df,
    print_dict,
    print_done,
    print_error,
    print_info,
    print_path,
    print_rule,
    print_section,
    print_step,
    print_summary_table,
    print_tree,
    print_warn,
    prompt,
    spinner,
    status_context,
    track,
)
from .exceptions import (
    ConfigurationError,
    DependencyError,
    ExtractionError,
    RegistrationError,
    RegistrationQualityError,
    SlideNotFoundError,
    UnsupportedFormatError,
    WSIProcessingError,
)
from .logging import (
    add_log_file,
    configure_logging,
    get_logger,
    logger,
    set_log_level,
)
from .magnification import (
    DEFAULT_TARGET_MAGNIFICATION,
    MagnificationPlan,
    build_magnification_plan,
    objective_magnification_from_properties,
)
from .output import OutputLayout, safe_name
from .slide import SlideReader
from .tissue import (
    brightness_saturation_is_tissue,
    is_tissue,
    optical_density_max_channel,
    optical_density_otsu_mask,
    pil_brightness_saturation_fraction,
    pil_intensity_fraction,
    pil_is_tissue,
    tissue_fraction,
    tissue_mask,
)

__all__ = [
    "DEFAULT_TARGET_MAGNIFICATION",
    "ConfigurationError",
    "DependencyError",
    "ExtractionError",
    "MagnificationPlan",
    "OutputLayout",
    "RegistrationError",
    "RegistrationQualityError",
    "SlideNotFoundError",
    "SlideReader",
    "UnsupportedFormatError",
    "WSIProcessingError",
    "add_log_file",
    "ask",
    "brightness_saturation_is_tissue",
    "build_magnification_plan",
    "configure_logging",
    "get_logger",
    "logger",
    "objective_magnification_from_properties",
    "optical_density_max_channel",
    "optical_density_otsu_mask",
    "pil_brightness_saturation_fraction",
    "pil_intensity_fraction",
    "pil_is_tissue",
    "print_banner",
    "print_code",
    "print_counts",
    "print_df",
    "print_dict",
    "print_done",
    "print_error",
    "print_info",
    "print_path",
    "print_rule",
    "print_section",
    "print_step",
    "print_summary_table",
    "print_tree",
    "print_warn",
    "prompt",
    "safe_name",
    "set_log_level",
    "spinner",
    "status_context",
    "tissue_fraction",
    "tissue_mask",
    "track",
    "is_tissue",
]
